defmodule CheerfulDonor.Repo.Migrations.AddedTypeInDonationsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:donations) do
      add :type, :text, null: false, default: "one_time"
    end
  end

  def down do
    alter table(:donations) do
      remove :type
    end
  end
end
