defmodule CheerfulDonor.Repo.Migrations.AddedTwoAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :status, :text, default: "pending"
      modify :currency, :text, default: "NGN"
    end

    alter table(:subscriptions) do
      modify :status, :text, default: "active"
    end

    alter table(:payouts) do
      modify :status, :text, default: "pending"
    end

    alter table(:donors) do
      modify :is_active, :boolean, default: true
    end

    alter table(:donations) do
      modify :status, :text, default: "pending"
      add :amount_paid, :bigint
      add :paystack_id, :text
    end

    alter table(:donation_intents) do
      modify :status, :text, default: "pending"
    end
  end

  def down do
    alter table(:donation_intents) do
      modify :status, :text, default: nil
    end

    alter table(:donations) do
      remove :paystack_id
      remove :amount_paid
      modify :status, :text, default: nil
    end

    alter table(:donors) do
      modify :is_active, :boolean, default: nil
    end

    alter table(:payouts) do
      modify :status, :text, default: nil
    end

    alter table(:subscriptions) do
      modify :status, :text, default: nil
    end

    alter table(:transactions) do
      modify :currency, :text, default: nil
      modify :status, :text, default: nil
    end
  end
end
