defmodule CheerfulDonor.Repo.Migrations.AddKindRoleFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :type, :text, null: false, default: "campaign"
    end
  end

  def down do
    alter table(:campaigns) do
      remove :type
    end
  end
end
