defmodule CheerfulDonor.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :payload, :map
      add :processed, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :bigint, null: false
      add :currency, :text, null: false
      add :status, :text, null: false
      add :reference, :text, null: false
      add :channel, :text
      add :fees, :bigint
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :donor_id, :uuid
      add :church_id, :uuid
      add :subscription_id, :uuid
      add :donation_id, :uuid
      add :payment_method_id, :uuid
    end

    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :bigint, null: false
      add :interval, :text, null: false
      add :status, :text, null: false
      add :next_charge_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :donor_id, :uuid
      add :church_id, :uuid
      add :payment_method_id, :uuid
    end

    create table(:payouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :bigint, null: false
      add :status, :text, null: false
      add :paid_at, :utc_datetime
      add :reference, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :church_id, :uuid
      add :bank_account_id, :uuid
    end

    create table(:payment_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :paystack_authorization_code, :text, null: false
      add :card_type, :text
      add :last4, :text
      add :exp_month, :bigint
      add :exp_year, :bigint
      add :bank, :text
      add :reusable, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :donor_id, :uuid
    end

    create table(:donors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:transactions) do
      modify :donor_id,
             references(:donors,
               column: :id,
               name: "transactions_donor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subscriptions) do
      modify :donor_id,
             references(:donors,
               column: :id,
               name: "subscriptions_donor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:payment_methods) do
      modify :donor_id,
             references(:donors,
               column: :id,
               name: "payment_methods_donor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:donors) do
      add :paystack_customer_id, :text
      add :phone, :text
      add :address, :text
      add :is_active, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "donors_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :church_id, :uuid
    end

    create table(:donations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :bigint, null: false
      add :currency, :text, null: false, default: "NGN"
      add :status, :text, null: false
      add :reference, :text, null: false
      add :message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :donor_id,
          references(:donors,
            column: :id,
            name: "donations_donor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :church_id, :uuid
      add :donation_intent_id, :uuid
      add :campaign_id, :uuid
      add :transaction_id, :uuid
    end

    create table(:donation_intents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :amount, :bigint, null: false
      add :currency, :text, null: false, default: "NGN"
      add :status, :text, null: false
      add :meta, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :donor_id,
          references(:donors,
            column: :id,
            name: "donation_intents_donor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :church_id, :uuid
      add :campaign_id, :uuid
      add :payment_method_id, :uuid
    end

    create table(:churches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:transactions) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "transactions_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :subscription_id,
             references(:subscriptions,
               column: :id,
               name: "transactions_subscription_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :donation_id,
             references(:donations,
               column: :id,
               name: "transactions_donation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :payment_method_id,
             references(:payment_methods,
               column: :id,
               name: "transactions_payment_method_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subscriptions) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "subscriptions_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :payment_method_id,
             references(:payment_methods,
               column: :id,
               name: "subscriptions_payment_method_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:payouts) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "payouts_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:donors) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "donors_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:donations) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "donations_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :donation_intent_id,
             references(:donation_intents,
               column: :id,
               name: "donations_donation_intent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:donation_intents) do
      modify :church_id,
             references(:churches,
               column: :id,
               name: "donation_intents_church_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:churches) do
      add :name, :text, null: false
      add :email, :text, null: false
      add :phone, :text
      add :address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:campaigns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:donations) do
      modify :campaign_id,
             references(:campaigns,
               column: :id,
               name: "donations_campaign_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :transaction_id,
             references(:transactions,
               column: :id,
               name: "donations_transaction_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:donation_intents) do
      modify :campaign_id,
             references(:campaigns,
               column: :id,
               name: "donation_intents_campaign_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :payment_method_id,
             references(:payment_methods,
               column: :id,
               name: "donation_intents_payment_method_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:campaigns) do
      add :title, :text, null: false
      add :description, :text
      add :goal_amount, :bigint
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :church_id,
          references(:churches,
            column: :id,
            name: "campaigns_church_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:bank_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payouts) do
      modify :bank_account_id,
             references(:bank_accounts,
               column: :id,
               name: "payouts_bank_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bank_accounts) do
      add :bank_name, :text, null: false
      add :account_number, :text, null: false
      add :account_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :church_id,
          references(:churches,
            column: :id,
            name: "bank_accounts_church_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bank_accounts, "bank_accounts_church_id_fkey")

    alter table(:bank_accounts) do
      remove :church_id
      remove :updated_at
      remove :inserted_at
      remove :account_name
      remove :account_number
      remove :bank_name
    end

    drop constraint(:payouts, "payouts_bank_account_id_fkey")

    alter table(:payouts) do
      modify :bank_account_id, :uuid
    end

    drop table(:bank_accounts)

    drop constraint(:campaigns, "campaigns_church_id_fkey")

    alter table(:campaigns) do
      remove :church_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :goal_amount
      remove :description
      remove :title
    end

    drop constraint(:donation_intents, "donation_intents_campaign_id_fkey")

    drop constraint(:donation_intents, "donation_intents_payment_method_id_fkey")

    alter table(:donation_intents) do
      modify :payment_method_id, :uuid
      modify :campaign_id, :uuid
    end

    drop constraint(:donations, "donations_campaign_id_fkey")

    drop constraint(:donations, "donations_transaction_id_fkey")

    alter table(:donations) do
      modify :transaction_id, :uuid
      modify :campaign_id, :uuid
    end

    drop table(:campaigns)

    alter table(:churches) do
      remove :updated_at
      remove :inserted_at
      remove :address
      remove :phone
      remove :email
      remove :name
    end

    drop constraint(:donation_intents, "donation_intents_church_id_fkey")

    alter table(:donation_intents) do
      modify :church_id, :uuid
    end

    drop constraint(:donations, "donations_church_id_fkey")

    drop constraint(:donations, "donations_donation_intent_id_fkey")

    alter table(:donations) do
      modify :donation_intent_id, :uuid
      modify :church_id, :uuid
    end

    drop constraint(:donors, "donors_church_id_fkey")

    alter table(:donors) do
      modify :church_id, :uuid
    end

    drop constraint(:payouts, "payouts_church_id_fkey")

    alter table(:payouts) do
      modify :church_id, :uuid
    end

    drop constraint(:subscriptions, "subscriptions_church_id_fkey")

    drop constraint(:subscriptions, "subscriptions_payment_method_id_fkey")

    alter table(:subscriptions) do
      modify :payment_method_id, :uuid
      modify :church_id, :uuid
    end

    drop constraint(:transactions, "transactions_church_id_fkey")

    drop constraint(:transactions, "transactions_subscription_id_fkey")

    drop constraint(:transactions, "transactions_donation_id_fkey")

    drop constraint(:transactions, "transactions_payment_method_id_fkey")

    alter table(:transactions) do
      modify :payment_method_id, :uuid
      modify :donation_id, :uuid
      modify :subscription_id, :uuid
      modify :church_id, :uuid
    end

    drop table(:churches)

    drop constraint(:donation_intents, "donation_intents_donor_id_fkey")

    drop table(:donation_intents)

    drop constraint(:donations, "donations_donor_id_fkey")

    drop table(:donations)

    drop constraint(:donors, "donors_user_id_fkey")

    alter table(:donors) do
      remove :church_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :address
      remove :phone
      remove :paystack_customer_id
    end

    drop constraint(:payment_methods, "payment_methods_donor_id_fkey")

    alter table(:payment_methods) do
      modify :donor_id, :uuid
    end

    drop constraint(:subscriptions, "subscriptions_donor_id_fkey")

    alter table(:subscriptions) do
      modify :donor_id, :uuid
    end

    drop constraint(:transactions, "transactions_donor_id_fkey")

    alter table(:transactions) do
      modify :donor_id, :uuid
    end

    drop table(:donors)

    drop table(:payment_methods)

    drop table(:payouts)

    drop table(:subscriptions)

    drop table(:transactions)

    drop table(:webhook_events)
  end
end
