defmodule CheerfulDonor.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :payment_provider, :text, null: false, default: "paystack"
    end

    create unique_index(:donations, [:donation_intent_id], name: "donations_unique_intent_index")
  end

  def down do
    drop_if_exists unique_index(:donations, [:donation_intent_id],
                     name: "donations_unique_intent_index"
                   )

    alter table(:transactions) do
      remove :payment_provider
    end
  end
end
