defmodule CheerfulDonor.Repo.Migrations.AddBankCodeToPayout do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payouts) do
      add :transfer_code, :text
    end

    alter table(:bank_accounts) do
      add :bank_code, :text, null: false
      add :recipient_code, :text
    end
  end

  def down do
    alter table(:bank_accounts) do
      remove :recipient_code
      remove :bank_code
    end

    alter table(:payouts) do
      remove :transfer_code
    end
  end
end
