defmodule CheerfulDonor.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:churches, [:user_id], name: "churches_unique_user_church_index")
  end

  def down do
    drop_if_exists unique_index(:churches, [:user_id], name: "churches_unique_user_church_index")
  end
end
