defmodule CheerfulDonor.Repo.Migrations.UpdateSubscriptionStructure do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :church_id,
          references(:churches,
            column: :id,
            name: "subscriptions_church_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "subscriptions_campaign_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:donations) do
      modify :donation_intent_id, :uuid, null: true
    end
  end

  def down do
    alter table(:donations) do
      modify :donation_intent_id, :uuid, null: false
    end

    drop constraint(:subscriptions, "subscriptions_church_id_fkey")

    drop constraint(:subscriptions, "subscriptions_campaign_id_fkey")

    alter table(:subscriptions) do
      remove :campaign_id
      remove :church_id
    end
  end
end
