defmodule :"Elixir.CheerfulDonor.Repo.Migrations.Add recurring fixes" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:donation_intents) do
      add :interval, :text
      add :type, :text, null: false, default: "one_time"
    end
  end

  def down do
    alter table(:donation_intents) do
      remove :type
      remove :interval
    end
  end
end
