defmodule CheerfulDonor.Repo.Migrations.AddSlugInCampaigns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :payment_provider, :text, null: false, default: "paystack"
    end

    create unique_index(:donations, [:donation_intent_id], name: "donations_unique_intent_index")

    create unique_index(:churches, [:user_id], name: "churches_unique_user_church_index")

    alter table(:campaigns) do
      add :slug, :text, null: false
    end

    create unique_index(:campaigns, [:slug], name: "campaigns_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:campaigns, [:slug], name: "campaigns_unique_slug_index")

    alter table(:campaigns) do
      remove :slug
    end

    drop_if_exists unique_index(:churches, [:user_id], name: "churches_unique_user_church_index")

    drop_if_exists unique_index(:donations, [:donation_intent_id],
                     name: "donations_unique_intent_index"
                   )

    alter table(:transactions) do
      remove :payment_provider
    end
  end
end
