defmodule :"Elixir.CheerfulDonor.Repo.Migrations.Add emailToken to subscriptions" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :email_token, :text
    end
  end

  def down do
    alter table(:subscriptions) do
      remove :email_token
    end
  end
end
